'use client';
import { useState, useRef } from 'react';
import { motion } from 'motion/react';
import {
  Sparkles, FileText, Building2, Briefcase, Link2,
  Upload, Save, Copy, Download, ChevronDown,
} from 'lucide-react';
import styles from './page.module.css';

const TONES = ['Professional', 'Confident', 'Friendly', 'Formal', 'Concise'];

// ── Hardcoded recent cover letters — replace with API data when ready ──────────
const RECENT_LETTERS = [
  { id: 1, company: 'Linear',  role: 'Product Designer',   date: 'May 14, 2026' },
  { id: 2, company: 'Vercel',  role: 'Frontend Engineer',  date: 'May 9, 2026'  },
  { id: 3, company: 'Notion',  role: 'Design Engineer',    date: 'May 2, 2026'  },
  { id: 4, company: 'Stripe',  role: 'Senior PM',          date: 'Apr 24, 2026' },
];
// ─────────────────────────────────────────────────────────────────────────────

const cardVariants = {
  hidden:  { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { type: 'spring', stiffness: 300, damping: 26 } },
};

export default function CoverLetterPage() {
  const [company, setCompany]                 = useState('');
  const [jobTitle, setJobTitle]               = useState('');
  const [jobLink, setJobLink]                 = useState('');
  const [jobDescription, setJobDescription]   = useState('');
  const [tone, setTone]                       = useState('Professional');
  const [generatedLetter, setGeneratedLetter] = useState('');
  const [isGenerating, setIsGenerating]       = useState(false);
  const [selectedResume, setSelectedResume]   = useState('');

  const resumeInputRef = useRef(null);

  const canGenerate = company.trim() && jobTitle.trim() && jobDescription.trim();

  const handleGenerate = async () => {
    if (!canGenerate || isGenerating) return;
    setIsGenerating(true);
    // TODO: call cover letter API
    setTimeout(() => {
      setGeneratedLetter(
        `Dear Hiring Manager,\n\nI am writing to express my strong interest in the ${jobTitle} position at ${company}. With my background and experience, I am confident in my ability to contribute meaningfully to your team.\n\n[Full letter will be generated by the API]\n\nSincerely,\n[Your Name]`
      );
      setIsGenerating(false);
    }, 1500);
  };

  const handleDescDrop = (e) => {
    e.preventDefault();
    const file = e.dataTransfer.files[0];
    if (file && file.type === 'text/plain') {
      const reader = new FileReader();
      reader.onload = (ev) => setJobDescription(ev.target.result);
      reader.readAsText(file);
    }
  };

  const handleCopy = () => {
    if (generatedLetter) navigator.clipboard.writeText(generatedLetter);
  };

  return (
    <div className={styles.page}>

      {/* ── Page header ──────────────────────────────────────── */}
      <div className={styles.pageHeader}>
        <h1 className={styles.heading}>AI Cover Letter Builder</h1>
        <p className={styles.subheading}>
          Generate personalized cover letters tailored to specific job applications
        </p>
      </div>

      {/* ── Two columns ──────────────────────────────────────── */}
      <div className={styles.columns}>

        {/* ── Left: form card ──────────────────────────────── */}
        <motion.div
          className={styles.card}
          variants={cardVariants}
          initial="hidden"
          animate="visible"
        >
          {/* Resume */}
          <div className={styles.field}>
            <label className={styles.fieldLabel}>
              <FileText className={styles.fieldIcon} />
              Resume
            </label>
            <div className={styles.resumeRow}>
              <div className={styles.selectWrap}>
                <select
                  className={styles.select}
                  value={selectedResume}
                  onChange={e => setSelectedResume(e.target.value)}
                >
                  <option value="">Select a resume…</option>
                </select>
                <ChevronDown className={styles.selectChevron} />
              </div>
              <button
                className={styles.uploadBtn}
                onClick={() => resumeInputRef.current?.click()}
              >
                <Upload className={styles.uploadIcon} />
                Upload
              </button>
              <input ref={resumeInputRef} type="file" accept=".pdf" hidden />
            </div>
          </div>

          {/* Company + Job Title */}
          <div className={styles.fieldRow}>
            <div className={styles.field}>
              <label className={styles.fieldLabel}>
                <Building2 className={styles.fieldIcon} />
                Company
              </label>
              <input
                className={styles.input}
                placeholder="e.g. Linear"
                value={company}
                onChange={e => setCompany(e.target.value)}
              />
            </div>
            <div className={styles.field}>
              <label className={styles.fieldLabel}>
                <Briefcase className={styles.fieldIcon} />
                Job Title
              </label>
              <input
                className={styles.input}
                placeholder="e.g. Product Designer"
                value={jobTitle}
                onChange={e => setJobTitle(e.target.value)}
              />
            </div>
          </div>

          {/* Job Link */}
          <div className={styles.field}>
            <label className={styles.fieldLabel}>
              <Link2 className={styles.fieldIcon} />
              Job Link <span className={styles.optional}>(optional)</span>
            </label>
            <input
              className={styles.input}
              placeholder="https://..."
              value={jobLink}
              onChange={e => setJobLink(e.target.value)}
            />
          </div>

          {/* Job Description */}
          <div className={styles.field}>
            <label className={styles.fieldLabel}>Job Description</label>
            <div
              className={styles.textareaWrap}
              onDragOver={e => e.preventDefault()}
              onDrop={handleDescDrop}
            >
              <textarea
                className={styles.textarea}
                placeholder="Paste the full job description here..."
                value={jobDescription}
                onChange={e => setJobDescription(e.target.value)}
                rows={8}
              />
              <div className={styles.textareaFooter}>
                <span className={styles.dragHint}>Drag &amp; drop a .txt file</span>
                <span className={styles.charCount}>{jobDescription.length} chars</span>
              </div>
            </div>
          </div>

          {/* Tone */}
          <div className={styles.field}>
            <label className={styles.fieldLabel}>Tone</label>
            <div className={styles.tones}>
              {TONES.map(t => (
                <button
                  key={t}
                  className={`${styles.tonePill} ${tone === t ? styles.tonePillActive : ''}`}
                  onClick={() => setTone(t)}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          {/* Generate */}
          <button
            className={styles.generateBtn}
            onClick={handleGenerate}
            disabled={!canGenerate || isGenerating}
          >
            <Sparkles className={styles.generateIcon} />
            {isGenerating ? 'Generating…' : 'Generate Cover Letter'}
          </button>
        </motion.div>

        {/* ── Right: output card ────────────────────────────── */}
        <motion.div
          className={`${styles.card} ${styles.outputCard}`}
          variants={cardVariants}
          initial="hidden"
          animate="visible"
          transition={{ delay: 0.05 }}
        >
          <div className={styles.outputHeader}>
            <div>
              <p className={styles.outputTitle}>Generated Cover Letter</p>
              <p className={styles.outputSub}>
                {generatedLetter ? 'Ready to use or edit below.' : 'Will appear here once generated'}
              </p>
            </div>
            <div className={styles.outputActions}>
              <button className={styles.actionBtn} disabled={!generatedLetter}>
                <Save className={styles.actionIcon} />
                Save draft
              </button>
              <button className={styles.actionBtn} disabled={!generatedLetter} onClick={handleCopy}>
                <Copy className={styles.actionIcon} />
                Copy
              </button>
              <button className={styles.actionBtn} disabled={!generatedLetter}>
                <Download className={styles.actionIcon} />
                Download PDF
              </button>
            </div>
          </div>

          <div className={styles.outputBody}>
            {generatedLetter ? (
              <textarea
                className={styles.outputTextarea}
                value={generatedLetter}
                onChange={e => setGeneratedLetter(e.target.value)}
              />
            ) : (
              <div className={styles.emptyState}>
                <div className={styles.emptyIconWrap}>
                  <Sparkles className={styles.emptyIcon} />
                </div>
                <p className={styles.emptyTitle}>Your cover letter will appear here</p>
                <p className={styles.emptySub}>
                  Fill in the job details and paste a description, then click<br />
                  Generate to draft a tailored letter in seconds.
                </p>
              </div>
            )}
          </div>
        </motion.div>

      </div>

      {/* ── Recent Cover Letters ──────────────────────────────── */}
      <div className={styles.recentSection}>
        <div className={styles.recentHeader}>
          <div>
            <p className={styles.recentTitle}>Recent Cover Letters</p>
            <p className={styles.recentSub}>Previously generated letters tied to companies and roles.</p>
          </div>
          <button className={styles.viewAllBtn}>View all</button>
        </div>

        <div className={styles.recentGrid}>
          {RECENT_LETTERS.map(letter => (
            <div key={letter.id} className={styles.recentCard}>
              <div className={styles.recentAvatar}>
                {letter.company.slice(0, 2).toUpperCase()}
              </div>
              <p className={styles.recentCompany}>{letter.company}</p>
              <p className={styles.recentRole}>{letter.role}</p>
              <p className={styles.recentDate}>{letter.date}</p>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
}
