'use client';
import { useState, useRef } from 'react';
import { motion } from 'motion/react';
import {
  Sparkles, FileText, Building2, Briefcase, Link2,
  Upload, Save, Copy, Download, ChevronDown,
} from 'lucide-react';
import styles from './page.module.css';

const TONES = ['Professional', 'Confident', 'Friendly', 'Formal', 'Concise'];

// ── Hardcoded recent cover letters — replace with API data when ready ──────────
const RECENT_LETTERS = [
  { id: 1, company: 'Linear',  role: 'Product Designer',   date: 'May 14' },
  { id: 2, company: 'Vercel',  role: 'Frontend Engineer',  date: 'May 9'  },
  { id: 3, company: 'Notion',  role: 'Design Engineer',    date: 'May 2'  },
  { id: 4, company: 'Stripe',  role: 'Senior PM',          date: 'Apr 24' },
];
// ─────────────────────────────────────────────────────────────────────────────

const formVariants   = {
  hidden:  { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { type: 'spring', stiffness: 300, damping: 26 } },
};
const outputVariants = {
  hidden:  { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { type: 'spring', stiffness: 300, damping: 26, delay: 0.07 } },
};

export default function CoverLetterPage() {
  const [company, setCompany]                 = useState('');
  const [jobTitle, setJobTitle]               = useState('');
  const [jobLink, setJobLink]                 = useState('');
  const [jobDescription, setJobDescription]   = useState('');
  const [tone, setTone]                       = useState('Professional');
  const [generatedLetter, setGeneratedLetter] = useState('');
  const [isGenerating, setIsGenerating]       = useState(false);
  const [selectedResume, setSelectedResume]   = useState('');

  const resumeInputRef = useRef(null);
  const canGenerate    = company.trim() && jobTitle.trim() && jobDescription.trim();

  const handleGenerate = async () => {
    if (!canGenerate || isGenerating) return;
    setIsGenerating(true);
    // TODO: call cover letter API
    setTimeout(() => {
      setGeneratedLetter(
        `Dear Hiring Manager,\n\nI am writing to express my strong interest in the ${jobTitle} position at ${company}. With my background and experience, I am confident in my ability to contribute meaningfully to your team.\n\n[Full letter will be generated by the API]\n\nSincerely,\n[Your Name]`
      );
      setIsGenerating(false);
    }, 1500);
  };

  const handleDescDrop = (e) => {
    e.preventDefault();
    const file = e.dataTransfer.files[0];
    if (file && file.type === 'text/plain') {
      const reader = new FileReader();
      reader.onload = (ev) => setJobDescription(ev.target.result);
      reader.readAsText(file);
    }
  };

  const handleCopy = () => {
    if (generatedLetter) navigator.clipboard.writeText(generatedLetter);
  };

  return (
    <div className={styles.page}>

      {/* ── Page header ──────────────────────────────────────── */}
      <div className={styles.pageHeader}>
        <p className={styles.subheading}>Generate tailored cover letters for any role.</p>
      </div>

      {/* ── Workspace ────────────────────────────────────────── */}
      <div className={styles.workspace}>

        {/* ── Left: form column ────────────────────────────── */}
        <motion.div
          className={styles.formColumn}
          variants={formVariants}
          initial="hidden"
          animate="visible"
        >
          <div className={`${styles.formCard} ${generatedLetter ? styles.formCardBack : ''}`}>

            {/* Resume */}
            <div className={styles.field}>
              <label className={styles.fieldLabel}>
                <FileText className={styles.fieldIcon} />
                Resume
              </label>
              <div className={styles.resumeRow}>
                <div className={styles.selectWrap}>
                  <select
                    className={styles.select}
                    value={selectedResume}
                    onChange={e => setSelectedResume(e.target.value)}
                  >
                    <option value="">Select a resume…</option>
                  </select>
                  <ChevronDown className={styles.selectChevron} />
                </div>
                <button
                  className={styles.uploadBtn}
                  onClick={() => resumeInputRef.current?.click()}
                >
                  <Upload className={styles.uploadIcon} />
                  Upload
                </button>
                <input ref={resumeInputRef} type="file" accept=".pdf" hidden />
              </div>
            </div>

            {/* Company + Job Title */}
            <div className={styles.fieldRow}>
              <div className={styles.field}>
                <label className={styles.fieldLabel}>
                  <Building2 className={styles.fieldIcon} />
                  Company
                </label>
                <input
                  className={styles.input}
                  placeholder="e.g. Linear"
                  value={company}
                  onChange={e => setCompany(e.target.value)}
                />
              </div>
              <div className={styles.field}>
                <label className={styles.fieldLabel}>
                  <Briefcase className={styles.fieldIcon} />
                  Job Title
                </label>
                <input
                  className={styles.input}
                  placeholder="e.g. Product Designer"
                  value={jobTitle}
                  onChange={e => setJobTitle(e.target.value)}
                />
              </div>
            </div>

            {/* Job Link */}
            <div className={styles.field}>
              <label className={`${styles.fieldLabel} ${styles.fieldLabelMuted}`}>
                <Link2 className={styles.fieldIcon} />
                Job Link <span className={styles.optional}>(optional)</span>
              </label>
              <input
                className={`${styles.input} ${styles.inputSm}`}
                placeholder="https://..."
                value={jobLink}
                onChange={e => setJobLink(e.target.value)}
              />
            </div>

            {/* Job Description */}
            <div className={styles.field}>
              <label className={styles.fieldLabel}>Job Description</label>
              <div
                className={styles.textareaWrap}
                onDragOver={e => e.preventDefault()}
                onDrop={handleDescDrop}
              >
                <textarea
                  className={styles.textarea}
                  placeholder="Paste the full job description here..."
                  value={jobDescription}
                  onChange={e => setJobDescription(e.target.value)}
                  rows={7}
                />
                <div className={styles.textareaFooter}>
                  <span className={styles.dragHint}>Drag &amp; drop a .txt file</span>
                  <span className={styles.charCount}>{jobDescription.length}</span>
                </div>
              </div>
            </div>

            {/* Tone */}
            <div className={styles.field}>
              <label className={`${styles.fieldLabel} ${styles.fieldLabelMuted}`}>Tone</label>
              <div className={styles.tones}>
                {TONES.map(t => (
                  <button
                    key={t}
                    className={`${styles.tonePill} ${tone === t ? styles.tonePillActive : ''}`}
                    onClick={() => setTone(t)}
                  >
                    {t}
                  </button>
                ))}
              </div>
            </div>

            {/* Generate */}
            <button
              className={styles.generateBtn}
              onClick={handleGenerate}
              disabled={!canGenerate || isGenerating}
            >
              <Sparkles className={styles.generateIcon} />
              {isGenerating ? 'Generating…' : 'Generate Cover Letter'}
            </button>
          </div>

          </motion.div>

        {/* ── Right: output column ──────────────────────────── */}
        <motion.div
          className={styles.outputColumn}
          variants={outputVariants}
          initial="hidden"
          animate="visible"
        >
          <div className={styles.outputCard}>

            {/* Output header */}
            <div className={styles.outputHeader}>
              <div>
                <p className={styles.outputTitle}>Cover Letter</p>
                <p className={styles.outputSub}>
                  {generatedLetter
                    ? `${company || 'Company'} — ${jobTitle || 'Role'}`
                    : 'Generated draft will appear here'}
                </p>
              </div>
              <div className={styles.outputActions}>
                <button className={styles.actionBtn} disabled={!generatedLetter}>
                  <Save className={styles.actionIcon} />
                  Save
                </button>
                <button className={styles.actionBtn} disabled={!generatedLetter} onClick={handleCopy}>
                  <Copy className={styles.actionIcon} />
                  Copy
                </button>
                <button className={styles.actionBtn} disabled={!generatedLetter}>
                  <Download className={styles.actionIcon} />
                  Export PDF
                </button>
              </div>
            </div>

            {/* Output body */}
            <div className={styles.outputBody}>
              {generatedLetter ? (
                <textarea
                  className={styles.outputDocument}
                  value={generatedLetter}
                  onChange={e => setGeneratedLetter(e.target.value)}
                  spellCheck
                />
              ) : (
                <div className={styles.emptyState}>
                  <FileText className={styles.emptyIcon} />
                  <p className={styles.emptyTitle}>Your draft will appear here once generated.</p>
                  <p className={styles.emptySub}>Fill in the details on the left and click Generate.</p>
                </div>
              )}
            </div>

          </div>
        </motion.div>

      </div>

      {/* ── Recent cover letters — horizontal strip ───────────── */}
      <div className={styles.recentSection}>
        <div className={styles.recentHeader}>
          <span className={styles.recentTitle}>Recent</span>
          <button className={styles.viewAllBtn}>View all</button>
        </div>
        <div className={styles.recentStrip}>
          {RECENT_LETTERS.map(letter => (
            <button key={letter.id} className={styles.recentCard}>
              <div className={styles.recentAvatar}>
                {letter.company.slice(0, 2).toUpperCase()}
              </div>
              <div className={styles.recentInfo}>
                <span className={styles.recentCompany}>{letter.company}</span>
                <span className={styles.recentRole}>{letter.role}</span>
              </div>
              <span className={styles.recentDate}>{letter.date}</span>
            </button>
          ))}
        </div>
      </div>

    </div>
  );
}
